version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file: .env
    environment:
      POSTGRES_URL: postgresql://adminDB:BOT778211@host.docker.internal:5433/plantIdDB
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ../plantId_frontend
      dockerfile: Dockerfile
      target: prod
    env_file: .env
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
